"use client";

// Tiny synthesized SFX — generated by scripts/gen-sfx.mjs into public/sfx/.
// Playback is fire-and-forget: browsers block audio before the first user
// gesture, and that's fine — the catch swallows the rejection silently.
const cache = new Map<string, HTMLAudioElement>();

export type SfxName =
  | "notify"
  | "claim"
  | "trade"
  | "win"
  | "lose"
  | "flip"
  | "roll"
  | "spin"
  | "launch";

export function playSfx(name: SfxName, volume = 0.5) {
  try {
    let a = cache.get(name);
    if (!a) {
      a = new Audio(`/sfx/${name}.wav`);
      cache.set(name, a);
    }
    a.volume = volume;
    a.currentTime = 0;
    void a.play().catch(() => {});
  } catch {
    // audio unavailable — ignore
  }
}
